# Generated by Django 3.0.4 on 2020-04-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(db_index=True, max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(db_index=True, max_length=128)),
                ('body', models.TextField(blank=True, max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveIntegerField(db_index=True, default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
                ('starred_by', models.ManyToManyField(blank=True, related_name='starred_by', to='main.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
                ('voted_by', models.ManyToManyField(related_name='voted_by', to='main.Account')),
            ],
        ),
    ]
